@startuml
'https://plantuml.com/class-diagram

class   BookEntity
class   BookDTO
class   BookDAO
class   BookService
class   BookController
class   BookRoute

class BookDAO {
+   Set<BookEntity>   getAll(Role.ANYONE role)
+   BookEntity        getById(int id, Role.ANYONE role)
+   Set<BookEntity>   getByName(String, Role.ANYONE role)
+   Set<BookEntity>   getByMaxPrice(int maxPrice, Role.ANYONE role)
+   Set<BookEntity>   getBtMinPrice(int minPrice, Role.ANYONE role)
+   Set<BookEntity>   getByPriceRange(int minPrice, int maxPrice, Role.ANYONE role)
+   putBook(BookEntity entity, Role.USER role)
+   patchBookUser(int bookId, Role.USER role, UserEntity user)
+   patchBookAdmin(int bookId, Role.ADMIN role, UserEntity admin)
+   deleteById(int bookId, Role.MODERATOR role)
}

class BookEntity{
@Getter
@Setter
+ int price
+ String title
+ String author
+ int bookId
+ int userId
+ BookEntity(int price, String title, String author, Role.USER role)
}

class BookDTO{
@Getter
+ String title
+ String author
+ int bookId
}

class BookService{
BookDTO put(BookEntity entity)
}

@enduml