@startuml
'https://plantuml.com/sequence-diagram

class UserEntity
class UserDTO
class UserDAO
class UserService
class UserController
class UserRoute

class UserEntity{
@Getter - password
@Setter
+ String username
+ int userId
+ String password [hashed]
+ Set<BookEntity> books
+ int getUserId()
+ Set<BookEntity> getBooks()
+ BookEntity getBookByTitle(String title)
+ BookEntity getBookById(int bookId)
}

class UserDTO{
@Getter
+ String username
+ int userId
+ Set<BookDTO> books
+ Set<BookDTO> getBooks()
+ String getUsername()
+ int getUserId()
}

class UserDAO{
+ UserDAO(EntityManager emf)
+ Set<UserEntity> getAll(Role.ADMIN role)
+ UserEntity getUserById(ROle.ADMIN role, int id)
+ UserEntity getByUsername(Role.ADMIN role, String username)
+ UserEntity getUserByBook(Role.ADMIN role, BookEntity entity)
+ UserEntity putUser(Role.ADMIN role, UserEntity entity)
+ UserEntity patchUser(Role.ADMIN role,UserEntity entity)
+ void deleteUser(Role.SUPER role, UserEntity entity)
}

class UserService{
+ UserService(UserDAO dao)
+ Set<UserDTO> getAll(Role.ADMIN role)
+ UserDTO getUserById(Role.ADMIN role, int id)
+ UserDTO getByUsername(Role.ADMIN role, String username)
+ UserDTO getUserByBook(Role.ANYONE role, BookDTO dto)
+ UserDTO putUser(Role.ADMIN role, UserDTO dto)
+ UserDTO patchUser(Role.ADMIN role, UserDTO dto)
+ void deleteUser(Role.SUPER role, UserDTO dto)
}

class UserController{
+ UserController(UserService service)
+ Handler getAll(Context ctx)
+ Handler getByUserId(Context ctx)
+ Handler getByBookId(Context ctx)
+ Handler getUserByBook(Context ctx)
+ Handler putUser(Context ctx)
+ Handler patchUser(Context ctx)
+ Handler deleteUser(Context ctx)
}

class UserRoute{
+ UserRoutes(UserController)
+ EndpointGroup getRoutes()
}

@enduml